### ISSUE TITLE
USER STORY: Search engine optimisation

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecomms#28]
As a **Site Owner** I can **know that my site has been optimised for search engines** so that **I receive more business**

# Acceptance Criteria

CHANGE A/C
 - All pages can be reached by a link from another findable page
 - Meta Description tags are used
 - Parent template has a relevant title
 - All paid or distrusted links have a "nofollow" relationship
 - All sponsored links have a "sponsored" relationship
 - A robots.txt is included
 - A sitemap is included
 - A 404 response page with an appropriate redirect for attempted access to non-existent content is included

# Tasks

- [ ] Create list of topics want to rank highly in SEO (see SEO CI webmarketing vid)
- [ ] Use [wordtracker] for suggestions (https://www.wordtracker.com/)
- [ ] Make sure all pages can be reached by a link from another findable page
- [ ] Make sure Meta Description tags are used
- [ ] Make sure Parent template has a relevant title
- [ ] Make sure a correct sitemap is included
- [ ] Make sure a correct robots.txt is included
- [ ] Add a button to the 404 page to return to the home page
- [ ] Ensure all text content supports the purpose of the application
- [ ] Ensure all paid or distrusted links have a "nofollow" relationship
- [ ] Ensure all sponsored links have a "sponsored" relationship
- [ ] Add relevant quality links
