### ISSUE TITLE
USER STORY: Sort the products by category

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/ecomms#6]
As a **Site User** I can **sort the goods on sale by relevant categories** so that **I can see easily navigate the goods**

# Acceptance Criteria

- I can choose a category of goods from the relevant page
- ADD CATEGORIES
- This displays the goods from the selected category

# Tasks

- [ ] Add query to URL
- [ ] Import Q and generate search query
- [ ] Manually test viewing all categories
